tasks:
  task_1:
    # id of the task. Must be unique
    id                       : task_1
    # task description of what this task will achieve
    task_description         : A test task that is created by sajal
    # source connection name
    source_connection_name   : mssql_conn
    # target connection name
    target_connection_name   : postgres_conn
    # query that will be directly executed on the source connection database
    raw_query                : select * from cars
    # the alias for the raw query result. You can query this alias
    raw_alias                : raw_car_alias
    # stage query. This query to be executed only on aliases
    stage_query              : select *, 'tata nexon' as car_name from raw_car_alias
    # the alias for the stage query result
    stage_alias              : stage_car_alias
    # target container name
    target_container_name    : cars_sajal
    # save_mode for the task
    save_mode                : replace